name: Test and publish

on:
  ["push","pull_request"]

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3.0.3
      with:
        dotnet-version: '6.x'
    - name : coverlet
      run: |
        dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
        mv Tests.FileStats/TestResults/*/coverage.info lcov.info
    - name: coveralls      
      uses: coverallsapp/github-action@v1.2.3
      with:
        github-token: ${{secrets.GITHUB_TOKEN }} 
        path-to-lcov: 'lcov.info'
    - name: Build
      run: ./build.sh
    - name: Upload binaries to release
      if: contains(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: filestats-win.zip
        asset_name: filestats-win.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Windows release zip"
