name: Test and publish

on:
  "push"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4.0.1
      with:
        dotnet-version: '8.x'

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: 'csharp'
        queries: +security-and-quality

    - name : coverlet
      run: |
        dotnet test --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=lcov
        mv Tests.FileStats/TestResults/*/coverage.info lcov.info

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3
      with:
        category: "/language:csharp"

    - name: coveralls      
      uses: coverallsapp/github-action@v2.3.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN }} 
        path-to-lcov: 'lcov.info'
    - name: Build
      run: ./build.sh
    - name: Upload binaries to release
      if: contains(github.ref, 'refs/tags/v')
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: filestats-win.zip
        asset_name: filestats-win.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Windows release zip"
